name: Deploy

on:
  push:
    branches:
      - master

env:
  GCS_BUCKET: emeris-com
  DOMAIN: emeris.com
  LOAD_BALANCER: emeris-websites

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with GCloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}"

      - name: Setup GCloud cli
        uses: google-github-actions/setup-gcloud@v0

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install (npm)
        run: npm install

      - name: Build Production
        run: npm run generate

      - name: Deploy
        run: gsutil -m rsync -d -R dist gs://$GCS_BUCKET

      - name: Invalidate Cache
        run: gcloud compute url-maps invalidate-cdn-cache $LOAD_BALANCER --host $DOMAIN --path "/*"
